### PR TITLE
Close #85. Transaction rollback

### LINKED ISSUE #85: Transaction rollback
We need to rollback all the effects produced by transaction when it fails.

### PR DESCRIPTION
**Pull request by pankratov**

### CODE REVIEW

File: vm/src/main/scala/pravda/vm/Vm.scala [hunk 1]
```diff
@@ -150,10 +150,12 @@ object Vm {
             } else {
               memory.push(addressToData(progAddress.get))
             }
+            aux()
```
Comment (fomkin) [inline vm/src/main/scala/pravda/vm/Vm.scala]: Looks like it was a critical bug not found yet :)

Comment (pankratov) [reply vm/src/main/scala/pravda/vm/Vm.scala]: yes. It was :( PR with these opcodes was merged a couple days before.

Comment (vovapolu) [reply vm/src/main/scala/pravda/vm/Vm.scala]: :smiling_imp: side-effects :smiling_imp:
